CREATE DATABASE CRUD;
USE CRUD;
CREATE TABLE CLASS(CID INT PRIMARY KEY,BLOCK CHAR(10));
CREATE TABLE STUDENT(
	SID INT PRIMARY KEY auto_increment,
    SNAME CHAR(25),
    SADDRESS CHAR(50),
    SCLASS INT,
    FOREIGN KEY(SCLASS) REFERENCES CLASS(CID) on delete cascade
);
