CREATE DATABASE BLOGSITE;
USE BLOGSITE;
-- User Attributes
CREATE TABLE USER(
	USERID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(15),
    LASTNAME VARCHAR(15),
    USERNAME VARCHAR(25) NOT NULL,
    PASSWORD VARCHAR(30),
    ROLE CHAR(10)
);
-- Category Attributes
CREATE TABLE CATEGORY(
	CATEGORYID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORYNAME VARCHAR(10) UNIQUE,
    POST INT
);
-- POST Attributes
CREATE TABLE POST (
    POSTID INT PRIMARY KEY AUTO_INCREMENT,
    POSTTITLE VARCHAR(25) NOT NULL,
    POSTDESCRIPTION TEXT NOT NULL,
    POSTIMAGE VARCHAR(25) DEFAULT NULL,
    CATEGORY INT NOT NULL,
    AUTHOR INT NOT NULL,
    FOREIGN KEY (AUTHOR) REFERENCES USER(USERID),
    FOREIGN KEY (CATEGORY) REFERENCES CATEGORY(CATEGORYID)
);
